export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCES = "REGISTER_SUCCES";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCES = "LOGIN_SUCCES";
export const LOGIN_ERROR = "LOGIN_ERROR";